services:
  fc-mongodb:
    image: mongo:6-jammy
    ports:
      - "27018:27017"
    volumes:
      - /srv/data/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "wake"
      MONGO_INITDB_ROOT_PASSWORD: "VERY_SECRET_PASSWORD"

volumes:
  fc_mongo_data:
