services:
  # ---------------------------------------------------------
  # 1. MONGODB
  # ---------------------------------------------------------
  fc-mongodb:
    image: mongo:4.4
    ports:
      - "27018:27017"
    volumes:
      - /srv/data/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "wake"
      MONGO_INITDB_ROOT_PASSWORD: "VERY_SECRET_PASSWORD"

  # ---------------------------------------------------------
  # 2. POSTGRESQL
  # ---------------------------------------------------------
  fc-postgres:
    image: postgres:15
    ports:
      - "5433:5432"
    volumes:
      - /srv/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "wake"
      POSTGRES_PASSWORD: "VERY_SECRET_PASSWORD"
      POSTGRES_DB: "edc"

volumes:
  fc_mongo_data:
  fc_postgres_data:
