version: "3.8"

secrets:
  mongo_root_password:
    external: true
  postgres_password:
    external: true

services:
  # ---------------------------------------------------------
  # 1. MONGODB
  # ---------------------------------------------------------
  fc-mongodb:
    image: mongo:6-jammy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "27018:27017"
    volumes:
      - /srv/data/mongodb:/data/db
    secrets:
      - mongo_root_password
    environment:
      MONGO_INITDB_ROOT_USERNAME: "wake"
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_root_password

  # ---------------------------------------------------------
  # 2. POSTGRESQL
  # ---------------------------------------------------------
  fc-postgres:
    image: postgres:15
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "5433:5432"
    volumes:
      - /srv/data/postgres:/var/lib/postgresql/data
    secrets:
      - postgres_password
    environment:
      POSTGRES_USER: "wake"
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: "mydatabase"

volumes:
  fc_mongo_data:
  fc_postgres_data:
