networks:
  base-ds-network:
    external: true

services:
  provider-mastral:
    container_name: provider-mastral
    image: ghcr.io/wake-ua/provider-base:latest
    volumes:
      - ./resources/configuration/configuration.properties:/provider-base-docker-configuration.properties:ro
      - ./resources/identity:/identity:ro
    ports:
      - "18191:18191"
      - "18193:18193"
      - "18194:18194"
    restart: on-failure:5
    networks:
      - base-ds-network
