networks:
  base-ds-network:
    external: true

services:
  provider-idearium:
    container_name: provider-idearium
    image: ghcr.io/wake-ua/provider-base:latest
    volumes:
      - ./config/idearium.properties:/provider-base-docker-configuration.properties:ro
      - ./config/idearium_creds.json:/creds.json:ro
    ports:
      - "15191:15191"
      - "15193:15193"
      - "15194:15194"
    restart: on-failure
    networks:
      - base-ds-network
