name: Build and Publish Consumer Image (Main)

on:
  push:
    branches:
    - "main"
    - "feature/deployment"
    paths:
      - 'commons/src/**'
      - 'iam-identity/src/**'
      - 'consumers/consumer/src/**'
      - 'consumers/consumer-base/Dockerfile'
      - '.github/workflows/consumer-build.yml'

concurrency:
  group: consumer-main
  cancel-in-progress: true

jobs:
  # ------------------------------
  # 1. BUILD & PUSH CONSUMER DOCKER IMAGE
  # ------------------------------
  build-and-push-consumer:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------- LOGIN GHCR --------
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # -------- GRADLE BUILD --------
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build consumer JAR
        run: |
          ./gradlew clean build
          
      # ---------------------------------

      - name: Set dynamic tags for Consumer
        id: vars
        run: |
          IMAGE_BASE_CONSUMER="ghcr.io/wake-ua/consumer-base"
          DATE=$(date +%Y%m%d)
          SHA_SHORT=$(echo "${GITHUB_SHA}" | cut -c1-7)

          # Tags for consumer image
          echo "CONSUMER_LATEST=${IMAGE_BASE_CONSUMER}:latest" >> $GITHUB_OUTPUT
          echo "CONSUMER_SHA=${IMAGE_BASE_CONSUMER}:${SHA_SHORT}" >> $GITHUB_OUTPUT
          echo "CONSUMER_DATE=${IMAGE_BASE_CONSUMER}:${DATE}" >> $GITHUB_OUTPUT

      # -------- DOCKER BUILD & PUSH --------
      - name: Build Docker image for Consumer
        run: |
          docker build \
            -t ${{ steps.vars.outputs.CONSUMER_LATEST }} \
            -t ${{ steps.vars.outputs.CONSUMER_SHA }} \
            -t ${{ steps.vars.outputs.CONSUMER_DATE }} \
            ./consumers/consumer-base

      - name: Push Consumer images
        run: |
          docker push ${{ steps.vars.outputs.CONSUMER_LATEST }}
          docker push ${{ steps.vars.outputs.CONSUMER_SHA }}
          docker push ${{ steps.vars.outputs.CONSUMER_DATE }}
      # ---------------------------------

      